---
- include: packages.yml

# http://hakunin.com/six-ansible-practices
- name: Ensure github.com is a known host
  lineinfile:
    dest: "~/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"
- name: Download pyenv installer
  get_url: >
      url=https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
      dest=/tmp/pyenv-installer
      mode=0700
      sha256sum={{pyenv_installer_sha256}}

- include: pyenv.yml

- name: Remove pyenv installer
  file: path=/tmp/pyenv-installer state=absent
